name: Build the library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:  
  VERSION: 0.1.${{github.run_number}}
  PROJECT_FILE: "Tardigrade.Client/Tardigrade.Client.fsproj"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: set user secrets
      run: |
        dotnet user-secrets list --id ${{ secrets.USER_SECRETS_ID }}
        dotnet user-secrets --id ${{ secrets.USER_SECRETS_ID }} set "API name" ${{ secrets.KEY_NAME }}
        dotnet user-secrets --id ${{ secrets.USER_SECRETS_ID }} set "API secret" ${{ secrets.KEY_SECRET }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: pack
      run: | 
        echo version = ${{ VERSION }}
        dotnet pack ${{ PROJECT_FILE }} --configuration Release --no-build -p:PackageVersion=${{ VERSION }}